"""HTTP transport, response validation, and coverage results."""

from __future__ import annotations

from contextlib import suppress
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from math import ceil
from typing import Any

import requests

from growr_cli import __version__
from growr_cli.models import EnrichmentResult


class ProviderError(ValueError):
    """A provider failure with safe details generated by growr."""


def provider_result(
    status,
    data=None,
    detail="",
) -> EnrichmentResult:
    """Timestamp one provider outcome without replacing missing data."""

    return EnrichmentResult(
        status, datetime.now(timezone.utc).isoformat(), data, detail
    )


def retry_delay(value) -> int | None:
    """Parse either Retry-After form without echoing header text."""

    if not isinstance(value, str) or len(value) > 128:
        return None
    if value.isascii() and value.isdecimal():
        return int(value) if len(value) <= 10 else None
    try:
        retry_at = parsedate_to_datetime(value)
        if retry_at.tzinfo is None:
            retry_at = retry_at.replace(tzinfo=timezone.utc)
        seconds = (retry_at - datetime.now(timezone.utc)).total_seconds()
        return max(0, ceil(seconds))
    except (TypeError, ValueError, OverflowError):
        return None


class HttpClient:
    """Own a reusable HTTP session for injected integrations."""

    def __init__(self, timeout_seconds) -> None:
        """Configure the session and a timeout for every request."""

        self.timeout_seconds = timeout_seconds
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Accept": "application/json",
                "User-Agent": "growr/%s" % __version__,
            }
        )

    def close(self) -> None:
        """Release pooled HTTP connections."""

        self.session.close()

    def get_json(
        self,
        url,
        params=None,
        headers=None,
        *,
        source="Provider",
        include_error_body=False,
    ) -> tuple[Any, str | None]:
        """Fetch JSON with credential-free transport failures."""

        try:
            response = self.session.get(
                url,
                params=params,
                headers=headers,
                timeout=self.timeout_seconds,
            )
        except requests.RequestException as error:
            # Exception text can expose authenticated URLs or headers.
            return None, (
                "%s request failed (%s)" % (source, type(error).__name__)
            )

        if not response.ok:
            status = "HTTP %s" % response.status_code
            detail = (
                status
                if source == "Provider"
                else "%s returned %s" % (source, status)
            )
            # Report throttling without retrying or blocking a CLI run.
            # Untrusted header text must not reach logs or reports.
            if response.status_code == 429:
                delay = retry_delay(response.headers.get("Retry-After"))
                if delay is not None:
                    detail += "; retry after %s seconds" % delay
            body = None
            if include_error_body:
                with suppress(ValueError):
                    body = response.json()
            return body, detail

        try:
            return response.json(), None
        except ValueError:
            return None, "%s returned invalid JSON" % source

    def get_records(
        self,
        url,
        params=None,
        headers=None,
        *,
        source="Provider",
    ) -> tuple[list[dict[str, Any]], str | None]:
        """Validate a record list before matching individual mints."""

        data, error = self.get_json(url, params, headers, source=source)
        if error:
            return [], error
        if not isinstance(data, list) or any(
            not isinstance(item, dict) for item in data
        ):
            return [], "%s returned an unexpected response shape" % source
        return data, None
